[package]
name = "rustacles-brokers"
version = "0.1.0"
description = "Message brokers which allow for powerful communication between Spectacles services."
documentation = "https://docs.rs/rustacles-brokers/"
keywords = ["discord", "spec"]
authors = ["Texlo-Dev <richrancy@gmail.com>"]
repository = "https://github.com/spec-tacles/rustacles"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "0.34.0"
log = "0.4.8"
futures-await-test = "0.3.0"
futures = "0.3.4"
async-tungstenite = "*"
async-std = "1.5.0"