[package]
name = "brokers"
version = "0.1.0"
authors = ["rich"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "0.34.0"
log = "0.4.8"
futures-await-test = "0.3.0"
futures = "0.3.4"
async-tungstenite = "*"
tokio = "0.2.13"